AWSTemplateFormatVersion: '2010-09-09'
Description: 'my-cool-app

  Sample SAM Template for my-cool-app

  '
Globals:
  Function:
    Environment:
      Variables:
        AWS_REGION:
          Ref: AWS::NoValue
        DYNAMODB_ENDPOINT:
          Ref: AWS::NoValue
        TABLE_NAME:
          Ref: DynamoDBTable
    Timeout: 5
Outputs:
  Api:
    Description: API Gateway endpoint URL for Prod
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
Resources:
  DynamoDBGetAccess:
    Properties:
      Description: Dynamodb Get access
      Path: /
      PolicyDocument:
        Statement:
        - Action:
          - dynamodb:Query*
          Effect: Allow
          Resource:
          - Fn::GetAtt:
            - DynamoDBTable
            - Arn
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy
  DynamoDBPutAccess:
    Properties:
      Description: Dynamodb Put access
      Path: /
      PolicyDocument:
        Statement:
        - Action:
          - dynamodb:Put*
          Effect: Allow
          Resource:
          - Fn::GetAtt:
            - DynamoDBTable
            - Arn
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy
  DynamoDBTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: Id
        AttributeType: N
      KeySchema:
      - AttributeName: Id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      SSESpecification:
        SSEEnabled: true
    Type: AWS::DynamoDB::Table
  GetFunction:
    Properties:
      AutoPublishAlias: live
      CodeUri: s3://my-cool-app-bucket-sam/69e31ca0149d5c13f3d2d6daf745aea2
      DeploymentPreference:
        Alarms:
        - Ref: GetFunctionAliasErrorMetricGreaterThanZeroAlarm
        - Ref: GetFunctionLatestVersionErrorMetricGreaterThanZeroAlarm
        Type: Canary10Percent5Minutes
      Events:
        APIEvent:
          Properties:
            Method: get
            Path: /tasks/{taskId}
          Type: Api
      Handler: app.getTask
      Policies:
      - Ref: DynamoDBGetAccess
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  GetFunctionAliasErrorMetricGreaterThanZeroAlarm:
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: Resource
        Value:
          Fn::Sub: ${GetFunction}:live
      - Name: FunctionName
        Value:
          Ref: GetFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
    Type: AWS::CloudWatch::Alarm
  GetFunctionLatestVersionErrorMetricGreaterThanZeroAlarm:
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: Resource
        Value:
          Ref: GetFunction.Version
      - Name: FunctionName
        Value:
          Ref: GetFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
    Type: AWS::CloudWatch::Alarm
  PutFunction:
    Properties:
      AutoPublishAlias: live
      CodeUri: s3://my-cool-app-bucket-sam/69e31ca0149d5c13f3d2d6daf745aea2
      DeploymentPreference:
        Alarms:
        - Ref: PutFunctionLatestVersionErrorMetricGreaterThanZeroAlarm
        - Ref: PutFunctionAliasErrorMetricGreaterThanZeroAlarm
        Type: Canary10Percent5Minutes
      Events:
        APIEvent:
          Properties:
            Method: put
            Path: /tasks/{taskId}
          Type: Api
      Handler: app.putTask
      Policies:
      - Ref: DynamoDBPutAccess
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  PutFunctionAliasErrorMetricGreaterThanZeroAlarm:
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: Resource
        Value:
          Fn::Sub: ${PutFunction}:live
      - Name: FunctionName
        Value:
          Ref: PutFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
    Type: AWS::CloudWatch::Alarm
  PutFunctionLatestVersionErrorMetricGreaterThanZeroAlarm:
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: Resource
        Value:
          Ref: PutFunction.Version
      - Name: FunctionName
        Value:
          Ref: PutFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
    Type: AWS::CloudWatch::Alarm
Transform: AWS::Serverless-2016-10-31
